#!/bin/sh
# Assign ownership of the console to the invoking user
# $OpenBSD: GiveConsole,v 1.3 2019/05/12 11:53:06 jsg Exp $
#

sleep 1
pkill feh
pkill xclock
pkill xmessage

chown $USER /dev/console
if [ -c /dev/drm0 ]; then
    chown $USER /dev/drm0
fi
if [ -c /dev/drmR128 ]; then
    chown $USER /dev/drmR128
fi
/usr/X11R6/bin/sessreg -a -l $DISPLAY -u none $USER
